Cinema Employees
ryszardnarwojsz/test19124 pull request #11
Opened 2022-01-17 21:59 UTC by ryszardnarwojsz

Cinema Employees task

2022-01-19 07:02 UTC, MateuszMarczak requested changes
Musimy popracować jeszcze nad Managerem. Te stałe tam nie są potrzebne, dodatkowo zwracasz tam wartoć stałej statycznej utworzonej na sztywno a nie tej odziedziczonej po BaseEmployee:) Może w BaseEmployee przydałby się jeszcze jedne konstruktor? np jeden z ustawionym basesalary na 3000 a drugi który go przyjmuje jako parametr?

2022-01-19 07:02 UTC, MateuszMarczak commented on CinemaEmployee/src/BaseEmployee.java
> +        this.baseSalary = baseSalary;
ustawiasz tutaj baseSalary chociaz w linicie 11 masz już ustawione na sztywno 3000. Wiec albo tutaj albo tam :)

2022-01-19 07:02 UTC, MateuszMarczak commented on CinemaEmployee/src/BaseEmployee.java
> +    public int getBaseSalary() {
za obliczenie pensji podstawowej powinna byc odpwoedzialna metoda calculateMonthlySalary(), także nie powinno być tego gettera. Nie musimy tworzyć getterów do każdego pola w klasie jesli nie będziemy ich wykorzystywać

2022-01-19 07:02 UTC, MateuszMarczak commented on CinemaEmployee/src/BaseEmployee.java
> +    public int getHiredPeriod() {
To super, że użyłes LocalDate :)

2022-01-19 07:02 UTC, MateuszMarczak commented on CinemaEmployee/src/BaseEmployee.java
> +    private int hiredDate;
te pole może być oznaczone jako final

2022-01-19 07:02 UTC, MateuszMarczak commented on CinemaEmployee/src/Manager.java
> +    private static final int baseSalary = 5000;
stałe statyczne piszemy wielkimi litereamy BASE_SALARY :)

2022-01-19 21:15 UTC, ryszardnarwojsz commented on CinemaEmployee/src/BaseEmployee.java
> +    public int getBaseSalary() {
Ale w zadaniu jest takie polecenie :) ?
Dla każdego pracownika zaimplementuj metody realizujące poniższe wymagania:
● zwróć kwotę podstawowego wynagrodzenia:

2022-01-19 22:20 UTC, ryszardnarwojsz commented on CinemaEmployee/src/BaseEmployee.java
> +        this.baseSalary = baseSalary;
Chciałem zrezygnować z podawania jakiegokolwiek wynagrodzenia podstawowego z ręki np. managera na poziomie tworzenia obiektu Manager/Sprzedawca a chyba żeby wprowadzić drugi konstruktor w BaseEmployee który przyjmuje parametr wynagrodzenia trzebaby było taki parametr dodać w argumentach konstruktora i później go wprowadzać przy tworzeniu obiektu np. manager. Może coś źle rozumiem

2022-01-21 16:27 UTC, MateuszMarczak commented on CinemaEmployee/src/BaseEmployee.java
> +    public int getBaseSalary() {
ehh, no faktycznie mój bład :D zwracam honor :D

2022-01-21 16:35 UTC, MateuszMarczak commented on CinemaEmployee/src/BaseEmployee.java
> +        this.baseSalary = baseSalary;
możesz dodać drugi konstruktor w baseEmoloyee a używając go w managerze ustawić go w konstruktorze Managera bez przekazywania go jako parametr w menagrzee, ja zrobilem cos takiego:
  BaseEmployee(final String name, final String lastName, final int yearOfHiring, final double salary) {
    this.name = name;
    this.lastName = lastName;
    this.yearOfHiring = yearOfHiring;
    this.salary = salary;
  }
  
  

  Manager(final String name, final String lastName, final int yearOfHiring) {
    super(name, lastName, yearOfHiring, MANAGER_BASE_SALARY);
    this.bonus = DEFAULT_BONUS;
  }

2022-01-26 16:09 UTC, MateuszMarczak requested changes

2022-01-26 16:09 UTC, MateuszMarczak commented on CinemaEmployee/src/Manager.java
> +        return MANAGER_BASE_SALARY;
stałe statyczne trakujemy jako opisaną jakąś stałą wartość, tutaj zamiast zwracać MANAGER_BASE_SALARY, zwróć baseSalary

2022-01-26 16:09 UTC, MateuszMarczak commented on CinemaEmployee/src/Manager.java
> +        Manager.BONUS = bonus;
nie używamy seterów do pól statycznych, więc porztrzebowalibyśmy zwykłego pola bonus to do którego możemy przypisac wartosć ze stałej statycznej np DEFAULT_BONUS

2022-01-26 16:09 UTC, MateuszMarczak commented on CinemaEmployee/src/BaseEmployee.java
> +    public BaseEmployee(String employeeName, String employeeSurname, String position, int hiredDate, final int salary) {
o to chodziło :)

2022-01-29 15:48 UTC, mtszpater approved these changes

2022-02-01 16:18 UTC, merged