My own list commits
ryszardnarwojsz/test19124 pull request #44
Opened 2022-02-06 14:16 UTC by ryszardnarwojsz

My own list task

2022-02-06 17:34 UTC, mtszpater commented on MyOwnList/src/MyList.java
> +    List<Integer> MyList = new ArrayList<>();
eee, co to panie :D Lista zbudowana na liście? Założ, że lista nie istnieje ;) Tutaj powinna być tablica.

btw. 'MyList' - od kiedy to tak piszemy zmienne z wielkiej litery?

2022-02-07 20:28 UTC, MateuszMarczak requested changes

2022-02-07 20:28 UTC, MateuszMarczak commented on MyOwnList/src/MyList.java
> +        return myList.length == 0;
przy takiej implementacji lista nigdy nie będzie pusta.

2022-02-07 20:28 UTC, MateuszMarczak commented on MyOwnList/src/MyList.java
> +        return myList.length;
a jak utworze nowa liste i nie dodam żadnego elementu to i tak będę miał listę która mówi że jest jeden element "0" :)

2022-02-07 20:30 UTC, MateuszMarczak approved these changes

2022-02-08 09:01 UTC, MateuszMarczak approved these changes

2022-02-12 13:49 UTC, merged